require 'open-uri'
require 'nokogiri'
require 'colorize'

require_relative './top-beers/version'
require_relative './top-beers/beer'
require_relative './top-beers/cli'
require_relative './top-beers/scraper'
require_relative './top-beers/brewery'
require_relative './top-beers/style'
